obj-$(CONFIG_TOUCHSCREEN_FT5x_FT6x_SUPPORT)        += ftall.o
ftall-objs +=focaltech_core.o \
   			 focaltech_ctl.o \
   			 focaltech_ex_fun.o \
   			 focaltech_flash.o \
   			 focaltech_Gesture.o \
   			 ft_gesture_lib_32 \
