obj-$(CONFIG_ACTEL_DIRECTC) += actel_directc.o
actel_directc-objs := dpG3alg.o \
					  dpcore.o \
					  dpfrom.o \
					  dpnvm.o \
					  dpsecurity.o \
					  dpG4alg.o \
					  dpchain.o \
					  dpjtag.o \
					  dpalg.o \
					  dpcom.o \
					  dpuser.o \
					  dputil.o
